version: '3.1'

services:
    wordpress:
        image: wordpress
        restart: always
        ports:
            - 2345:80
        env_file:
            - .env
        volumes:
            - ./wordpress:/var/www/html

    db:
        image: 'mariadb'
        restart: always
        env_file:
            - .env
        volumes:
            - wordpress-data:/var/lib/mysql
            # Pour lancer un dump automatiquement au montage du conteneur
            - ./DumpSQL/data.sql:/docker-entrypoint-initdb.d/data.sql



    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1

volumes:
    wordpress-data:
